"""
Author: Keerthana Nallamotu <kn6412@princeton.edu>
Contributors: 
Created: 2024-9-14
Updated: 2025-10-10


Description: 

Tool to query MSigDB annotations with a list of gene symbols"""

from __future__ import annotations

import time

from src.state import State
from src.tools.base import Node
from pathlib import Path
from typing import Dict, Iterable, List, Sequence
import json
from .utils import extract_geneSetNames

DEBUG = True

REPO_ROOT = Path(__file__).resolve().parents[3]
LOCAL_DBS = REPO_ROOT / "local_dbs"
MSIGDB = LOCAL_DBS / "gene_centered_msigdb.v2025.1.Hs.json.txt"

CATEGORIES = {
    'H':  'Hallmark gene sets - Summarize and represent specific well-defined biological states or processes and display coherent expression. These gene sets were generated by a computational methodology based on identifying overlaps between gene sets in other MSigDB collections and retaining genes that display coordinate expression.',
    'C1': 'Positional gene sets - Gene sets corresponding to human chromosome cytogenetic bands.', 
    'C2': 'Curated gene sets - Gene sets in this collection are curated from various sources, including online pathway databases and the biomedical literature. Many sets are also contributed by individual domain experts.',
    'C3': "Regulatory target gene sets - Gene sets representing potential targets of regulation by transcription factors or microRNAs. The sets consist of genes grouped by elements they share in their non-protein coding regions. The elements represent known or likely cis-regulatory elements in promoters and 3'-UTRs.",
    'C4': 'Computational gene sets - Computational gene sets defined by mining large collections of cancer-oriented expression data.',
    'C6': 'Oncogenic signature gene sets - Gene sets that represent signatures of cellular pathways which are often dis-regulated in cancer. The majority of signatures were generated directly from microarray data from NCBI GEO or from internal unpublished profiling experiments involving perturbation of known cancer genes.',
    'C7': 'Immunologic signature gene sets - Gene sets that represent cell states and perturbations within the immune system.',
    'C8': 'C8 cell type signature gene sets - Gene sets that contain curated cluster markers for cell types identified in single-cell sequencing studies of human tissue.'
}


def msigdb_agent(state: "State") -> "State":
    """
    LangGraph node that annotates each gene with MSigDB data.

    Parameters
    ----------
    state
        Current graph state.

    Returns
    -------
    State
        Updated state with the msigdb fields filled.
        
    """
    gene_entities = state.get("gene_entities") or {}

    with open(MSIGDB, "r") as file:
        msigdata = json.load(file)

    for gene_name, gene in gene_entities.items():
        if not gene_name or gene_name not in msigdata:
            continue

        summary_lines: List[str] = []

        for collection, desc in CATEGORIES.items():
            annots_list = extract_geneSetNames(msigdata, gene.symbol, collection)
            
            summary_lines.append(f"*MSigDB: Collection {collection} ({desc}) for {gene.symbol}: " + ", ".join(annots_list) + ".")
            gene.add_msigdb_annotated_terms(collection, annots_list)

        if summary_lines:
            gene.update_text_summaries(" ".join(summary_lines))
        
            gene.add_tool("MSigDB")

    if DEBUG:
        print(f"[MSigDB] Predictions fetched")

    return 
NODES: tuple[Node, ...] = (
    Node(
        name="MSigDB",
        entry_point=msigdb_agent,
        description="Fetches MSigDB annotations for input genes across collections (H, C1–C8), including hallmark biological processes, positional cytogenetic bands per gene, curated pathways, regulatory target information (e.g. transcription-factor binding in promoter region of the gene and miRNAs predicted to target this gene), computational signatures from cancer-oriented expression data, oncogenic signatures of pathways dysregulated in cancer, immunologic signatures, and cell-type markers.",
    ),
)
